// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NetworkMessage
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public enum ServerPackets : ushort
{
  SC_LoginAns = 1,
  SC_AccountInfo = 2,
  SC_WorldEnterNotify = 3,
  SC_CreatePlayer = 4,
  SC_CreatePlayers = 5,
  SC_RemovePlayer = 6,
  SC_UpdatePosition = 7,
  SC_PlayerUpdate = 8,
};

public enum ClientPackets : ushort
{
  CS_LoginReq = 1,
  CS_WorldJoinReq = 2,
  CS_UpdatePosition = 3,
};


}
